**Task:Create arrays with all the data types available in numpy**

**NumPy Data Types**

-  integer
-  boolean
-  unsigned integer
-  float
-  complex float
-  timedelta
-  datetime
-  object
-  string
-  unicode string
-  fixed chunk of memory for other type ( void )

In [2]:
import numpy as np

In [3]:
x = np.array([5,4,3,2,1])
print(x)
x.dtype

[5 4 3 2 1]


dtype('int32')

In [4]:
x = np.array([1,2,3,4,5,6], dtype='bool_')
print(x)
x.dtype

[ True  True  True  True  True  True]


dtype('bool')

In [5]:
x= np.array([250202], dtype='uint16')
print(x)
x.dtype

[53594]


dtype('uint16')

In [6]:
x= np.array([1.1, 1.2,1.3, 1.4, 1.5, 1.6])
print(x)
x.dtype

[1.2 2.3 3.4 4.5 5.6]


dtype('float64')

In [7]:
x = np.array([1+2j, 2+3j, 4+5j, 5+6j])
print(x)
x.dtype

[1.+2.j 2.+3.j 4.+5.j 5.+6.j]


dtype('complex128')

In [9]:
x=np.timedelta64(5, 'D')
print(x)
x.dtype

5 days


dtype('<m8[D]')

In [10]:
x=np.array(['2002-02-25', '2001-03-17', '1973-05-01'], dtype='datetime64')
x

array(['2002-02-25', '2001-03-17', '1973-05-01'], dtype='datetime64[D]')

In [11]:
x = np.array([2,4,6,8], dtype='O')
x

array([2, 4, 6, 8], dtype=object)

In [12]:
x = np.array(['Tokyo', 'Berlin', 'Nairobi', 'Oslo'])
print(x)
x.dtype

['Tokyo' 'Berlin' 'Nairobi' 'Oslo']


dtype('<U7')

In [13]:
x = np.array([u'\u03bcm', u'\u2202r', u'\u2206\u03bb'], dtype='U')
x

array(['μm', '∂r', '∆λ'], dtype='<U2')

In [ ]:
x=np.void([], dtype='V')
x